apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ocm-registry-tls-certs
spec:
  externalSecretName: "ocm-registry-tls-certs-es"
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["ocm-system", "mpas-system", "mpas-ocm-applications", "default"]
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: secret-store-name
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: ocm-registry-tls-certs
    data:
    - secretKey: ca.crt
      remoteRef:
        key: ocm-registry-tls-certs
        property: ca.crt
    - secretKey: tls.crt
      remoteRef:
        key: ocm-registry-tls-certs
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: ocm-registry-tls-certs
        property: tls.key
